FROM node:10

RUN git clone https://github.com/obmarg/libsysconfcpus.git && \
  cd libsysconfcpus && \
  ./configure && \
  make && \
  make install && \
  cd ../ && \
  rm -rf libsysconfcpus

RUN yarn global add elm elm-test create-elm-app --no-progress
